name: "ADR (Decision/Proposal)"
description: "Record a significant architectural decision and its consequences."
title: "ADR: <decision title>"
labels: ["Type: ADR"]
body:
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Background and forces at play.
      validations:
        required: true
  - type: textarea
    id: options
    attributes:
      label: Options Considered
      description: List the alternatives with pros/cons.
  - type: textarea
    id: decision
    attributes:
      label: Decision
      description: State the decision clearly.
      validations:
        required: true
  - type: textarea
    id: consequences
    attributes:
      label: Consequences
      description: Trade-offs, follow-ups, and risks.
  - type: dropdown
    id: status
    attributes:
      label: Status
      options:
        - Proposed
        - Accepted
        - Superseded
        - Rejected
      default: 0
  - type: checkboxes
    id: breaking
    attributes:
      label: Breaking Change?
      options:
        - label: This decision introduces a breaking change
  - type: textarea
    id: links
    attributes:
      label: Links (PRs, Issues)
