from __future__ import annotations
from typing import Mapping, Iterable, Any
from dataclasses import dataclass


@dataclass
class RunStore:
    def capabilities(self) -> dict[str, bool]: ...
    def new_run(self, config: Mapping[str, Any]) -> str: ...
    def new_episode(self, run_id: str, match_id: str) -> str: ...
    def log_step(
        self,
        episode_id: str,
        idx: int,
        record: Mapping[str, Any],
    ) -> None: ...
    def end_episode(self, episode_id: str, outcome: str) -> None: ...
    def get_episode(self, episode_id: str) -> Iterable[Mapping[str, Any]]: ...
    def put_artifact(self, run_id: str, kind: str, uri: str, sha256: str) -> str: ...
