# Maps Scryfall catalog → dim table/column
dims:
  - catalog: formats
    table: dim.dim_format
    column: format_name
  - catalog: supertypes
    table: dim.dim_supertype
    column: supertype
  - catalog: card-types
    table: dim.dim_card_type
    column: card_type
  - catalog: card-subtypes
    table: dim.dim_subtype
    column: subtype
  - catalog: finishes
    table: dim.dim_finish
    column: finish
  - catalog: currencies
    table: dim.dim_currency
    column: currency_code
  - catalog: languages
    table: dim.dim_language
    column_map:
      code: lang_code
      name: name
  - catalog: watermarks
    table: dim.dim_watermark
    column: watermark
  - catalog: artist-names
    table: dim.dim_artist
    column: name
  - catalog: card-names
    table: dim.dim_card_name
    column: name
