SET NOCOUNT ON;
WITH x(code) AS (SELECT 'W' UNION ALL SELECT 'U' UNION ALL SELECT 'B' UNION ALL SELECT 'R' UNION ALL SELECT 'G' UNION ALL SELECT 'C')
INSERT INTO dbo.dim_color(code)
SELECT code FROM x WHERE NOT EXISTS (SELECT 1 FROM dbo.dim_color d WHERE d.code=x.code);
